name: CI | On PR assigned dispatch to OpenSILEX-phis-docker-ci

on:
 pull_request:
    types: [assigned]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Repository Dispatch peter-evans/repository-dispatch@v1
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ASA-OpenSILEX/opensilex-phis-docker-ci
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
